### ISSUE TITLE
In Groups, what's the best way to supply 'empty' group

### ISSUE THREAD

**Issue by jbaksta** [cea-hpc/clustershell#533]
Somewhat of weird request, but I have a need to have empty group. I've been just using `None` to keep the library from getting a traceback, but we populate a group yaml file with something like:

```yaml
x1000:
  c0: nid[0001-32]
  c0r3: nid[0001-16] 
  c0r7: nid[0017-32]
  c1: None
  ...
```

This is more for `cluset` type operations rather than `clush` operations specifically, but it's nice to provide some mechanism for empty set, but I don't know if there is a best mechanism for this or not. Leaving it empty gives a traceback. `NULL` also can't be used. I've thought maybe `False`, but still not great. So just looking how to mark an empty set as part of the configuration file. I'll continue scanning the docs, but I've not found anything (yet).
